### ISSUE TITLE
Pre-Process Environmental Parameters Failing

### ISSUE THREAD

**Issue by aagervasi** [SouthForkResearch/conductivity#18]
With Conductivity tolset versions 0.5.4 and dev_v1.0.4 I am getting the same error, that looks like it could be something wrong with the data (which I can investigate further myself if it is), but I am not sure. Something is causing the zonal statistics to be unable to calculate. I used the input "catch_final_noerrors" which is a version of the upstream catchments where I removed catchments with an error code of 1.

Please see C:\SFR\Arielle\Projects\mxds\UpperYakima on the Merlin computer for a log of the issues and the layers which point to the applicable data inside C:\SFR\Arielle\Projects\conductivity\Yakima\UpperYakima

**Comment by aagervasi** [comment]
![preprocessenvirparamerror](https://user-images.githubusercontent.com/25061462/31915640-0ff8f28c-b804-11e7-998d-f9bcf26e635e.png)

**Comment by jesselangdon** [comment]
I reviewed LineOIDs 241 and 242, and the catchment polygons associated with them (based on where the error occurred, just after completing the summary for LineOID 241).  In the attached screen shot, you can see that stream segment highlighted in yellow, and the associated catchment polygon highlighted in purple. 

I'm pretty sure what's happening is that those funky-looking catchments are not lining up with the centroids for the parameter rasters, so that's causing problems with the Zonal Statistics process in the tool.  There's a whole series of those long skinny catchment polygons, probably because that's a lake or other water body.

When we run the Catchment Tool, an arbitrary threshold of area values is associated with "small" catchment polygons, and any polygon that has an area value that is lower than that threshold get's tagged as an "error". But in reality, you can see the limitation of that. These particular polygons technically have spatial areas larger than the threshold I set, but they are still "bad" polygons.

![catchment_error](https://user-images.githubusercontent.com/2524993/31948117-d8181c94-b88a-11e7-9646-63cf6e60b4b9.png)

**Comment by jesselangdon** [comment]
Closing this, since this is actually an issue with the Catchment Tool.
